## 1.	Write a Python Program to Add Two Matrices

In [1]:
# Program to add two matrices
# using numpy
 
import numpy as np
  
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


## 2.	Write a Python Program to Multiply Two Matrices

In [2]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
# 3x4 matrix
B = [[1,2,3,4],
     [5,6,7,8],
     [2,4,6,8]]
# result is 3x4
result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]

# iterate through rows of Matrix A
for i in range(len(A)):
    # iterate through columns of Matrix B
    for j in range(len(B[0])):
        # iterate through rows of Matrix B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

print('Multiplied Matrix:')
for r in result:
    print(r)

Multiplied Matrix:
[17, 26, 35, 44]
[41, 62, 83, 104]
[65, 98, 131, 164]


## 3.	Write a Python Program to Transpose a Matrix

In [3]:
X = [[12,7],
    [4 ,5],
    [3 ,8]]

result = [[0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
       result[j][i] = X[i][j]

for r in result:
   print(r)

[12, 4, 3]
[7, 5, 8]


## 4.	Write a Python Program to Sort Words in Alphabetic Order